<?php
/**
 * @var $this \PackagedUi\FusionDemo\Layout\Layout
 */

use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

?>
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Dispatch::instance()->store()->generateHtmlIncludes(
    ResourceStore::TYPE_CSS
  ) ?>
</head>
<body class="demo-page">
<?= $this->getContent(); ?>
<?= Dispatch::instance()->store()->generateHtmlIncludes(
  ResourceStore::TYPE_JS
); ?>
</body>
</html>
